% run_Panels_bcd_Plot.m
%
% Generate publication-quality heatmap figures for Panels (b), (c), (d)
% Shows % of sites that gain healthy barrier state (B* = 1) under attenuation
%
% Requires: data/panel_b_all_sites.csv, panel_c_irreversible.csv, panel_d_reversible.csv
%           (generated by run_Panels_bcd_DataGeneration.m)
%
% Author: Jamie Lee
% Date: October 14, 2025

clear; clc; close all;

fprintf('╔═══════════════════════════════════════════════════════╗\n');
fprintf('║        Panels (b-d): Generating Heatmap Figures      ║\n');
fprintf('╚═══════════════════════════════════════════════════════╝\n\n');

%% Load data
fprintf('Loading data...\n');

if ~exist('data/panel_b_all_sites.csv', 'file')
    error('Data files not found! Please run run_Panels_bcd_DataGeneration.m first');
end

panel_b = readmatrix('data/panel_b_all_sites.csv');
panel_c = readmatrix('data/panel_c_irreversible.csv');
panel_d = readmatrix('data/panel_d_reversible.csv');

fprintf('  ✓ Loaded all data files\n\n');

%% Configuration
SA_folds = [1, 10, 20];
SE_folds = [1, 10, 20];

% Create sepia colormap (brown/tan gradient)
sepia_colors = [
    0.15, 0.08, 0.03;   % Dark brown (low %)
    0.35, 0.22, 0.12;
    0.55, 0.40, 0.28;
    0.70, 0.58, 0.45;
    0.82, 0.72, 0.62;
    0.92, 0.86, 0.80    % Light tan (high %)
];
sepia_map = interp1(linspace(0, 1, size(sepia_colors, 1)), sepia_colors, linspace(0, 1, 256));

% Create output folder
if ~exist('figures', 'dir'), mkdir('figures'); end

%% Create figure with 3 panels
fig = figure('Position', [100, 100, 1600, 450], 'Color', 'white');

%% Panel (b): All damaged sites
subplot(1, 3, 1);
create_heatmap(panel_b, SA_folds, SE_folds, sepia_map, 'All Damaged Sites');

%% Panel (c): Irreversible sites
subplot(1, 3, 2);
create_heatmap(panel_c, SA_folds, SE_folds, sepia_map, 'Irreversible Sites');

%% Panel (d): Reversible sites
subplot(1, 3, 3);
create_heatmap(panel_d, SA_folds, SE_folds, sepia_map, 'Reversible Sites');

%% Save figure
fprintf('Saving figure...\n');
saveas(fig, 'figures/Panels_bcd_Attenuation_Heatmaps.png');
saveas(fig, 'figures/Panels_bcd_Attenuation_Heatmaps.fig');
fprintf('  ✓ figures/Panels_bcd_Attenuation_Heatmaps.png\n');
fprintf('  ✓ figures/Panels_bcd_Attenuation_Heatmaps.fig\n\n');

fprintf('╔═══════════════════════════════════════════════════════╗\n');
fprintf('║                   FIGURES COMPLETE                    ║\n');
fprintf('╚═══════════════════════════════════════════════════════╝\n');

%% Helper function to create individual heatmap
function create_heatmap(data, SA_folds, SE_folds, colormap_data, plot_title)
    % Display heatmap
    imagesc(SA_folds, SE_folds, data);
    
    % Apply sepia colormap
    colormap(colormap_data);
    caxis([0, 100]);
    
    % Formatting
    set(gca, 'YDir', 'normal');
    set(gca, 'XTick', SA_folds, 'YTick', SE_folds);
    set(gca, 'FontSize', 14);  % Bigger tick labels
    set(gca, 'TickLength', [0, 0]);
    set(gca, 'LineWidth', 1.2);
    set(gca, 'XColor', 'black', 'YColor', 'black');  % Force axis colors to black
    
    % Clean, simple labels - bigger and black
    xlabel('SA Attenuation', 'FontSize', 14, 'FontWeight', 'bold', 'Color', [0, 0, 0]);
    ylabel('SE Attenuation', 'FontSize', 14, 'FontWeight', 'bold', 'Color', [0, 0, 0]);
    title(plot_title, 'FontSize', 14, 'FontWeight', 'bold', 'Color', [0, 0, 0]);
    
    % Add percentage text inside each cell
    for i = 1:length(SE_folds)
        for j = 1:length(SA_folds)
            value = round(data(i, j));
            
            % Choose text color for readability
            if value < 45
                text_color = [1, 1, 1];  % White
            else
                text_color = [0, 0, 0];  % Black
            end
            
            text(SA_folds(j), SE_folds(i), sprintf('%d', value), ...
                 'HorizontalAlignment', 'center', ...
                 'VerticalAlignment', 'middle', ...
                 'FontSize', 16, ...
                 'FontWeight', 'bold', ...
                 'Color', text_color);
        end
    end
    
    box on;
end